USE TestDb;
BEGIN TRANSACTION;
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID(N'PRODUCTVERSION') IS NOT NULL
	DROP TABLE [STOREHOUSE].[PRODUCTVERSION];
GO
CREATE TABLE [STOREHOUSE].[PRODUCTVERSION]
(
	[ID]				UNIQUEIDENTIFIER NOT NULL,
	[PRODUCT_ID]		UNIQUEIDENTIFIER NOT NULL,
	[NAME]				VARCHAR(255) NOT NULL,
	[DESCRITION]		VARCHAR(MAX) DEFAULT NULL,
	[CREATINGDATE]		DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
	[WIDTH]				REAL NOT NULL,
	[HEIGHT]			REAL NOT NULL,
	[LENGTH]			REAL NOT NULL,
) ON [PRIMARY];
GO
ALTER TABLE [STOREHOUSE].[PRODUCTVERSION] ADD CONSTRAINT
	STOREHOUSE_PRODUCTVERSION_WIDTH_POSITIVE CHECK([WIDTH] > 0);
GO
ALTER TABLE [STOREHOUSE].[PRODUCTVERSION] ADD CONSTRAINT
	STOREHOUSE_PRODUCTVERSION_HEIGHT_POSITIVE CHECK([HEIGHT] > 0);
GO		    
ALTER TABLE [STOREHOUSE].[PRODUCTVERSION] ADD CONSTRAINT
	STOREHOUSE_PRODUCTVERSION_LENGTH_POSITIVE CHECK([LENGTH] > 0);
GO
ALTER TABLE [STOREHOUSE].[PRODUCTVERSION] ADD CONSTRAINT
	STOREHOUSE_PRODUCTVERSION_ID_PK PRIMARY KEY([ID] ASC);
GO
ALTER TABLE [STOREHOUSE].[PRODUCTVERSION] ADD CONSTRAINT STOREHOUSE_PRODUCTVERSION_PRODUCT_ID_FK
	FOREIGN KEY ([PRODUCT_ID]) REFERENCES [STOREHOUSE].[PRODUCT]([ID]) ON DELETE CASCADE;
GO
CREATE NONCLUSTERED INDEX STOREHOUSE_PRODUCTVERSION_NAME_NIX ON [STOREHOUSE].[PRODUCTVERSION]([NAME] ASC)
WITH
(
	ALLOW_ROW_LOCKS = ON,
	ALLOW_PAGE_LOCKS = ON
);
GO
CREATE NONCLUSTERED INDEX STOREHOUSE_PRODUCTVERSION_CREATINGDATE_NIX ON [STOREHOUSE].[PRODUCTVERSION]([CREATINGDATE] ASC)
WITH
(
	ALLOW_ROW_LOCKS = ON,
	ALLOW_PAGE_LOCKS = ON
);
GO
CREATE NONCLUSTERED INDEX STOREHOUSE_PRODUCTVERSION_WIDTH_NIX ON [STOREHOUSE].[PRODUCTVERSION]([WIDTH] ASC)
WITH
(
	ALLOW_ROW_LOCKS = ON,
	ALLOW_PAGE_LOCKS = ON
);
GO
CREATE NONCLUSTERED INDEX STOREHOUSE_PRODUCTVERSION_HEIGHT_NIX ON [STOREHOUSE].[PRODUCTVERSION]([HEIGHT] ASC)
WITH
(
	ALLOW_ROW_LOCKS = ON,
	ALLOW_PAGE_LOCKS = ON
);
GO
CREATE NONCLUSTERED INDEX STOREHOUSE_PRODUCTVERSION_LENGTH_NIX ON [STOREHOUSE].[PRODUCTVERSION]([LENGTH] ASC)
WITH
(
	ALLOW_ROW_LOCKS = ON,
	ALLOW_PAGE_LOCKS = ON
);
GO
COMMIT TRANSACTION;